### ISSUE TITLE
readme "az.js requires Node.js v6.9.0 or greater"

### ISSUE THREAD

**Issue by chrisdias** [lostintangent/azjs#12]
I think you need v7+? With 6.9.? installed i get this, works with Node v7.8.0.

``` bash
~/src/node-todo$ azjs
/usr/local/lib/node_modules/azjs/lib/index.js:6
async function down (client) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/azjs/bin/cli.js:3:20)
```

**Comment by lostintangent** [comment]
@chrisdias Yeah you are right. I used `async/await` but I'd prefer to either transpile that or remove it in order to support 6.9+. This is part of the work that I was mentioning needed to get done before this was entirely worth publishing :)

**Comment by lostintangent** [comment]
The dependency on `async/await` has been removed, and the CLI now supports Node v6.9+ as advertised :)
